services:
  bidding:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      args:
        - SERVICE_BIN=bidding
    deploy:
      replicas: 3
    ports:
      - "8081-8083:8080"
    volumes:
      - ./logs:/var/app/logs/bidding.log
